# Generated by Django 5.2.3 on 2025-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
