# Generated by Django 5.2.3 on 2025-09-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0003_merchantstore_archived_at_merchantstore_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("card", "Credit/Debit (On-site)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[("test", "Test"), ("live", "Live")],
                        default="test",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="merchant.merchantstore",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "provider", "-updated_at"],
            },
        ),
    ]
