# Generated by Django 5.2.3 on 2025-09-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0004_merchantpaymentmethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
