# Generated by Django 5.2.3 on 2025-09-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0005_alter_orderitem_name_alter_orderitem_unit_price"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="product",
            table="core_product",
        ),
    ]
