# Generated by Django 5.2.3 on 2026-03-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0008_alter_merchantstore_owner_alter_merchantstore_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchantstore",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
