# Generated by Django 5.2.3 on 2026-03-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0010_storecategory_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="digital_file",
            field=models.FileField(
                blank=True, null=True, upload_to="digital_products/"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("physical", "Physical"), ("digital", "Digital")],
                default="physical",
                max_length=10,
            ),
        ),
    ]
