# Generated by Django 5.2.3 on 2026-04-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0012_mallzone_merchantstore_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="featured_slot",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional manual featured slot position within the zone (1-5).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
