# Generated by Django 5.2.3 on 2026-05-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0013_merchantstore_admin_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="storefront_image",
            field=models.ImageField(
                blank=True,
                help_text="Admin-controlled storefront entrance image for this merchant.",
                null=True,
                upload_to="storefronts/",
            ),
        ),
    ]
