# Generated by Django 5.2.3 on 2026-06-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0014_merchantstore_storefront_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zip",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
