# Generated by Django 5.2.3 on 2026-06-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0015_order_customer_email_order_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(default=False),
        ),
    ]
