# Generated by Django 5.2.3 on 2026-06-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "merchant",
            "0016_product_low_stock_threshold_product_stock_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(default="processing", max_length=30),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
