# Generated by Django 5.2.3 on 2026-06-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0017_order_delivered_at_order_shipped_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="average_prep_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="business_zip",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="delivery_minimum",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="delivery_radius_miles",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="offers_local_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="offers_pickup",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="offers_shipping",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_method",
            field=models.CharField(default="shipping", max_length=30),
        ),
    ]
