# Generated by Django 5.2.3 on 2026-07-11 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0018_merchantstore_average_prep_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="alert_acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_ready_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("awaiting_acceptance", "Awaiting Merchant Acceptance"),
                    ("accepted", "Accepted"),
                    ("preparing", "Preparing"),
                    ("picking", "Picking Items"),
                    ("packing", "Packing"),
                    ("ready_for_pickup", "Ready for Pickup"),
                    ("driver_requested", "Driver Requested"),
                    ("driver_assigned", "Driver Assigned"),
                    ("customer_pickup_ready", "Customer Pickup Ready"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("fulfilled", "Fulfilled"),
                    ("declined", "Declined"),
                    ("canceled", "Canceled"),
                ],
                default="awaiting_acceptance",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfillment_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="merchant_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="ready_for_pickup_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="MerchantFulfillmentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("accepting", "Accepting Orders"),
                            ("busy", "Busy"),
                            ("paused", "Temporarily Paused"),
                            ("closed", "Closed"),
                        ],
                        default="accepting",
                        max_length=20,
                    ),
                ),
                (
                    "merchant_type",
                    models.CharField(
                        choices=[
                            ("retail", "Retail / Product Merchant"),
                            ("restaurant", "Restaurant / Food Merchant"),
                            ("creator", "Creator Merchandise"),
                            ("florist", "Florist / Custom Preparation"),
                            ("service", "Service Merchant"),
                            ("other", "Other"),
                        ],
                        default="retail",
                        max_length=20,
                    ),
                ),
                ("pause_message", models.CharField(blank=True, max_length=255)),
                ("sound_alerts_enabled", models.BooleanField(default=True)),
                ("browser_notifications_enabled", models.BooleanField(default=True)),
                ("email_alerts_enabled", models.BooleanField(default=True)),
                (
                    "default_preparation_minutes",
                    models.PositiveIntegerField(default=15),
                ),
                ("last_status_change_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_settings",
                        to="merchant.merchantstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Fulfillment Setting",
                "verbose_name_plural": "Merchant Fulfillment Settings",
            },
        ),
    ]
