# Generated by Django 5.2.3 on 2026-07-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "merchant",
            "0019_order_alert_acknowledged_at_order_estimated_ready_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="interior_theme",
            field=models.CharField(
                choices=[
                    ("signature", "MajicMall Signature Showroom"),
                    ("fashion_boutique", "Luxury Fashion Boutique"),
                    ("tech_gallery", "Black Glass Tech Gallery"),
                    ("food_hall", "Majestic Food Hall"),
                    ("music_lounge", "Music Studio Lounge"),
                    ("automotive_gallery", "Luxury Automotive Gallery"),
                    ("creator_studio", "Creator Gallery Studio"),
                    ("sports_arena", "Championship Sports Shop"),
                    ("theater_lobby", "Premiere Theater Lobby"),
                    ("kids_adventure", "Kids Adventure Shop"),
                    ("travel_lounge", "World Travel Lounge"),
                ],
                default="signature",
                help_text="Controls the visual environment customers experience after entering the storefront.",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="merchantstore",
            name="storefront_image",
            field=models.ImageField(
                blank=True,
                help_text="Merchant storefront entrance image. The image must professionally represent the business and visually match the intended MajicMall Megaverse Zone.",
                null=True,
                upload_to="storefronts/",
            ),
        ),
    ]
