# Generated by Django 5.2.3 on 2026-07-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0020_merchantstore_interior_theme_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantstore",
            name="business_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="business_address_line_2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="business_city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="merchantstore",
            name="business_state",
            field=models.CharField(blank=True, default="", max_length=2),
        ),
    ]
