# Generated by Django 5.2.3 on 2026-07-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchant", "0021_merchantstore_business_address_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MajesticCoinWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="majestic_coin_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MajesticCoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("award", "Award"),
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("purchase", "Purchase"),
                            ("adjustment", "Adjustment"),
                        ],
                        default="award",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                (
                    "reference",
                    models.CharField(
                        help_text="Unique reference that prevents duplicate transactions.",
                        max_length=150,
                        unique=True,
                    ),
                ),
                ("balance_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="merchant.majesticcoinwallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MerchantMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_plan",
                    models.CharField(
                        choices=[
                            ("vision", "Vision"),
                            ("pro", "Pro"),
                            ("elite", "Elite"),
                            ("enterprise", "Enterprise"),
                            ("majestic", "Majestic"),
                            ("foundation", "Foundation Merchant"),
                        ],
                        default="vision",
                        max_length=20,
                    ),
                ),
                (
                    "previous_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vision", "Vision"),
                            ("pro", "Pro"),
                            ("elite", "Elite"),
                            ("enterprise", "Enterprise"),
                            ("majestic", "Majestic"),
                            ("foundation", "Foundation Merchant"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "transition_plan",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vision", "Vision"),
                            ("pro", "Pro"),
                            ("elite", "Elite"),
                            ("enterprise", "Enterprise"),
                            ("majestic", "Majestic"),
                            ("foundation", "Foundation Merchant"),
                        ],
                        default="",
                        help_text="Plan scheduled to begin after a complimentary or promotional membership ends.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("foundation", "Foundation"),
                            ("grace", "Grace Period"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("member_since", models.DateTimeField()),
                ("anniversary_date", models.DateField()),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("complimentary_until", models.DateField(blank=True, null=True)),
                ("foundation_expires_on", models.DateField(blank=True, null=True)),
                ("last_plan_change_at", models.DateTimeField(blank=True, null=True)),
                ("is_foundation_member", models.BooleanField(default=False)),
                ("foundation_pass_verified", models.BooleanField(default=False)),
                (
                    "foundation_member_number",
                    models.CharField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("majestic_coins_awarded", models.BooleanField(default=False)),
                (
                    "majestic_coins_awarded_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_records",
                        to="merchant.merchantstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant Membership",
                "verbose_name_plural": "Merchant Memberships",
                "ordering": ["-member_since"],
            },
        ),
        migrations.CreateModel(
            name="MerchantMembershipHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("created", "Membership Created"),
                            ("upgrade", "Plan Upgrade"),
                            ("downgrade", "Plan Downgrade"),
                            ("renewal", "Membership Renewal"),
                            ("extension", "Complimentary Extension"),
                            ("status", "Status Change"),
                            ("payment", "Payment Change"),
                            ("admin", "Administrative Change"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "previous_plan",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("new_plan", models.CharField(blank=True, default="", max_length=20)),
                (
                    "previous_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("new_status", models.CharField(blank=True, default="", max_length=20)),
                ("effective_date", models.DateTimeField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="merchant.merchantmembership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membership History",
                "verbose_name_plural": "Membership Histories",
                "ordering": ["-effective_date", "-id"],
            },
        ),
    ]
