# Generated by Django 5.2.3 on 2026-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="service_radius_miles",
            field=models.PositiveIntegerField(default=10),
        ),
    ]
