# Generated by Django 5.2.3 on 2026-07-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_deliverypartner_service_radius_miles"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="home_zip",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
