# Generated by Django 5.2.3 on 2026-07-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_deliverypartner_home_zip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryjob",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Delivery Job",
                "verbose_name_plural": "Delivery Jobs",
            },
        ),
        migrations.AlterModelOptions(
            name="deliverypartner",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Delivery Partner",
                "verbose_name_plural": "Delivery Partners",
            },
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="contractor_agreement_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="contractor_agreement_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="contractor_agreement_version",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="onboarding_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
