# Generated by Django 5.2.3 on 2026-07-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_deliveryjob_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="address_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="address_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="state",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="street_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
