# Generated by Django 5.2.3 on 2026-07-11 15:49

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_deliverypartner_account_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="documents_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="documents_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="driver_license_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=delivery.models.driver_verification_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="insurance_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=delivery.models.driver_verification_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="license_plate",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=delivery.models.driver_verification_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_make",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=delivery.models.driver_verification_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_registration_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=delivery.models.driver_verification_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
