# Generated by Django 5.2.3 on 2026-07-11 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_deliverypartner_documents_reviewed_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverypartner",
            name="documents_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_driver_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="driver_license_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="insurance_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="profile_photo_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_information_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_photo_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="vehicle_registration_reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverypartner",
            name="verification_review_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal review notes, missing-document details, or requested corrections.",
            ),
        ),
    ]
