# Generated by Django 5.2.3 on 2025-08-25 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sponsor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "screen_type",
                    models.CharField(
                        choices=[
                            ("Majic", "Majic"),
                            ("Nostalgia", "Nostalgia"),
                            ("Fantasy", "Fantasy"),
                            ("Indie", "Indie"),
                            ("Experience", "Experience"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="merchant_logos/"
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("elite", "Elite"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("runtime", models.CharField(blank=True, max_length=50)),
                ("rating", models.CharField(blank=True, max_length=10)),
                ("trailer_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="movies/"),
                ),
                ("is_premiere", models.BooleanField(default=False)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="movies/videos/"),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="core.moviescreen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                ("used", models.BooleanField(default=False)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="core.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
