# Generated by Django 5.2.3 on 2026-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_communitymember"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
