# Generated by Django 5.2.3 on 2026-06-02 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieScreen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("sponsor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "screen_type",
                    models.CharField(
                        choices=[
                            ("Majic", "Majic"),
                            ("Nostalgia", "Nostalgia"),
                            ("Fantasy", "Fantasy"),
                            ("Indie", "Indie"),
                            ("Experience", "Experience"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "duration",
                    models.IntegerField(
                        blank=True, help_text="Duration in minutes", null=True
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="movies/"),
                ),
                ("trailer_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=100)),
                ("rating", models.CharField(blank=True, max_length=20)),
                ("cast", models.TextField(blank=True)),
                ("sponsor", models.CharField(blank=True, max_length=150)),
                ("is_premiere", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movies",
                        to="theater.moviescreen",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-is_premiere", "-created_at"],
            },
        ),
    ]
