# Generated by Django 5.2.3 on 2026-07-26 00:01

import advertising.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal campaign name.", max_length=200
                    ),
                ),
                (
                    "advertiser_name",
                    models.CharField(
                        blank=True,
                        help_text="Merchant, organization, artist, sponsor, or advertiser.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Campaign objective, message, and internal notes.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time the campaign may begin.",
                        null=True,
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time the campaign should stop.",
                        null=True,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional total campaign budget.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Private notes for MajicMall Media Network staff.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advertising_campaigns_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Campaign",
                "verbose_name_plural": "Advertising Campaigns",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AdvertisingCreative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("billboard", "Digital Billboard"),
                            ("banner", "Banner Advertisement"),
                            ("image", "Image Advertisement"),
                            ("audio", "Audio Commercial"),
                            ("video", "Video Advertisement"),
                            ("theater_preroll", "Theater Pre-Roll"),
                            ("radio_spot", "Music Zone Radio Spot"),
                            ("mobile_promotion", "Mobile Promotion"),
                            ("public_announcement", "Public Announcement"),
                            ("other", "Other Creative"),
                        ],
                        db_index=True,
                        default="banner",
                        max_length=30,
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=advertising.models.creative_upload_path,
                        validators=[
                            advertising.models.validate_creative_file_extension
                        ],
                    ),
                ),
                (
                    "external_media_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional externally hosted media or streaming URL.",
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        blank=True,
                        help_text="Where visitors should go when they click the advertisement.",
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=255)),
                (
                    "call_to_action",
                    models.CharField(
                        blank=True,
                        help_text="Examples: Visit Store, Learn More, Buy Tickets.",
                        max_length=80,
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessibility description for visual advertisements.",
                        max_length=255,
                    ),
                ),
                (
                    "target_zones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Temporary list of zone names or slugs. A direct zone relationship can be added in a later push.",
                    ),
                ),
                (
                    "placement_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Placement identifiers such as home_billboard, directory_banner, or theater_preroll.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers receive higher display priority.",
                    ),
                ),
                (
                    "play_frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Relative rotation frequency for this creative.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional duration for audio or video creatives.",
                        null=True,
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional creative-specific start date and time.",
                        null=True,
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional creative-specific end date and time.",
                        null=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("impressions", models.PositiveBigIntegerField(default=0)),
                ("clicks", models.PositiveBigIntegerField(default=0)),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Approval, rejection, or production notes.",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advertising_creatives_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advertising_creatives_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="advertising.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Advertising Creative",
                "verbose_name_plural": "Advertising Creatives",
                "ordering": ("priority", "-created_at"),
            },
        ),
    ]
