# Generated by Django 5.2.3 on 2026-08-06 04:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0001_initial"),
        ("digital_property", "0005_digitalproperty_inventory_tier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("scheduled", "Scheduled"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CampaignPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "agreed_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="advertising.campaign",
                    ),
                ),
                (
                    "digital_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_placements",
                        to="digital_property.digitalproperty",
                    ),
                ),
                (
                    "lease_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_placements",
                        to="digital_property.leaseplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Placement",
                "verbose_name_plural": "Campaign Placements",
                "ordering": (
                    "start_at",
                    "digital_property__display_order",
                    "digital_property__name",
                ),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "digital_property"),
                        name="unique_campaign_digital_property",
                    )
                ],
            },
        ),
    ]
