# Generated by Django 5.2.3 on 2026-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertising", "0003_campaign_approved_at_campaign_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignplacement",
            name="booking_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive Property"),
                    ("rotating", "Rotating Position"),
                ],
                db_index=True,
                default="rotating",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="campaignplacement",
            name="positions_reserved",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of rotating advertising positions purchased. Exclusive bookings always reserve the full property.",
            ),
        ),
    ]
