# Generated by Django 5.2.3 on 2026-07-29 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_property", "0002_leaseplan"),
        ("merchant", "0022_majesticcoinwallet_majesticcointransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_code",
                    models.CharField(
                        help_text="Permanent inventory code, such as MM-BB-0001.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=170, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "location_label",
                    models.CharField(
                        blank=True,
                        help_text="Visible location description inside MajicMall Megaverse.",
                        max_length=180,
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=1920, help_text="Recommended creative width in pixels."
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=1080, help_text="Recommended creative height in pixels."
                    ),
                ),
                ("supports_image", models.BooleanField(default=True)),
                ("supports_video", models.BooleanField(default=False)),
                ("interactive", models.BooleanField(default=False)),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("leased", "Leased"),
                            ("maintenance", "Maintenance"),
                            ("coming_soon", "Coming Soon"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lease_plans",
                    models.ManyToManyField(
                        blank=True,
                        related_name="digital_properties",
                        to="digital_property.leaseplan",
                    ),
                ),
                (
                    "mall_zone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for global properties such as the homepage hero.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_properties",
                        to="merchant.mallzone",
                    ),
                ),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="digital_properties",
                        to="digital_property.propertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digital Property",
                "verbose_name_plural": "Digital Properties",
                "ordering": ["display_order", "name"],
            },
        ),
    ]
