# Generated by Django 5.2.3 on 2026-07-29 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_property", "0003_digitalproperty"),
        ("merchant", "0022_majesticcoinwallet_majesticcointransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lease_number",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Permanent public lease reference generated automatically.",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reserved", "Reserved"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="First calendar date covered by this lease."
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        help_text="Final calendar date covered by this lease."
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Final amount paid for this lease.",
                        max_digits=12,
                    ),
                ),
                ("auto_renew", models.BooleanField(default=False)),
                (
                    "campaign_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional merchant-facing advertising campaign name.",
                        max_length=180,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal administrative notes about this lease.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "digital_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_leases",
                        to="digital_property.digitalproperty",
                    ),
                ),
                (
                    "lease_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_leases",
                        to="digital_property.leaseplan",
                    ),
                ),
                (
                    "merchant_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_leases",
                        to="merchant.merchantstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Lease",
                "verbose_name_plural": "Property Leases",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["digital_property", "status"],
                        name="dp_lease_property_status_idx",
                    ),
                    models.Index(
                        fields=["merchant_store", "status"],
                        name="dp_lease_merchant_status_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="dp_lease_date_range_idx",
                    ),
                ],
            },
        ),
    ]
