# Generated by Django 5.2.3 on 2026-08-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_property", "0004_propertylease"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproperty",
            name="inventory_tier",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("signature", "Majestic Square Signature"),
                ],
                db_index=True,
                default="standard",
                help_text="Standard, Premium, or Majestic Square Signature inventory.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="digitalproperty",
            name="minimum_spend",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                help_text="Minimum total campaign budget required when this property is selected.",
                max_digits=12,
            ),
        ),
    ]
