# Generated by Django 5.2.3 on 2026-08-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_property", "0005_digitalproperty_inventory_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalproperty",
            name="display_seconds",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Number of seconds each advertisement remains visible during a rotation.",
            ),
        ),
        migrations.AddField(
            model_name="digitalproperty",
            name="inventory_mode",
            field=models.CharField(
                choices=[
                    ("exclusive", "Exclusive"),
                    ("rotating", "Rotating"),
                    ("hybrid", "Hybrid"),
                ],
                db_index=True,
                default="hybrid",
                help_text="Exclusive allows one advertiser, Rotating allows shared positions, and Hybrid supports either option.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="digitalproperty",
            name="rotation_capacity",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Maximum number of advertiser positions available in the rotation.",
            ),
        ),
    ]
