# Generated by Django 5.2.3 on 2026-07-28 22:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenLevelReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=70, unique=True)),
                (
                    "referral_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Percentage of a qualifying membership payment.",
                        max_digits=6,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Citizen Level reward",
                "verbose_name_plural": "Citizen Level rewards",
                "ordering": ("display_order", "name"),
            },
        ),
        migrations.CreateModel(
            name="MajesticCoinSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coin_name", models.CharField(default="Majestic Coin", max_length=80)),
                ("coin_symbol", models.CharField(default="MC", max_length=12)),
                ("currency_code", models.CharField(default="USD", max_length=3)),
                (
                    "coin_value",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.1000"),
                        help_text="Platform value represented by one Majestic Coin.",
                        max_digits=12,
                    ),
                ),
                (
                    "minimum_redemption_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=18
                    ),
                ),
                (
                    "maximum_daily_redemption_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=18
                    ),
                ),
                ("referral_rewards_enabled", models.BooleanField(default=True)),
                ("merchant_rewards_enabled", models.BooleanField(default=True)),
                ("creator_rewards_enabled", models.BooleanField(default=True)),
                ("purchase_rewards_enabled", models.BooleanField(default=False)),
                ("redemption_enabled", models.BooleanField(default=False)),
                ("bonus_events_enabled", models.BooleanField(default=True)),
                ("require_payment_confirmation", models.BooleanField(default=True)),
                (
                    "reward_hold_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Recommended holding period before a pending reward is posted.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Majestic Coin settings",
                "verbose_name_plural": "Majestic Coin settings",
            },
        ),
        migrations.CreateModel(
            name="MajestianWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "available_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "pending_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "lifetime_earned_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "lifetime_redeemed_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "lifetime_reversed_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "lifetime_expired_coins",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("restricted", "Restricted"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "opportunity_score",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Internal contribution score reserved for future Majestian recognition and leadership programs.",
                    ),
                ),
                ("last_transaction_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="majestian_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Majestian Wallet",
                "verbose_name_plural": "Majestian Wallets",
                "ordering": ("user_id",),
            },
        ),
        migrations.CreateModel(
            name="CoinTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("citizen_referral", "Citizen recommendation"),
                            ("merchant_referral", "Merchant recommendation"),
                            ("creator_referral", "Creator recommendation"),
                            ("purchase_reward", "Purchase reward"),
                            ("creator_revenue", "Creator revenue"),
                            ("ad_revenue", "Advertising revenue"),
                            ("sponsorship", "Sponsorship revenue"),
                            ("foundation_bonus", "Foundation bonus"),
                            ("community_reward", "Community reward"),
                            ("promotional_bonus", "Promotional bonus"),
                            ("redemption", "Redemption"),
                            ("expiration", "Expiration"),
                            ("admin_adjustment", "Administrative adjustment"),
                            ("reversal", "Reversal"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "coin_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Always stored as a positive quantity.",
                        max_digits=20,
                    ),
                ),
                (
                    "coin_value_snapshot",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value of one MC when this transaction was created.",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dollar value represented when the transaction was created.",
                        max_digits=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("reference_type", models.CharField(blank=True, max_length=100)),
                ("reference_id", models.CharField(blank=True, max_length=150)),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        help_text="Prevents a qualifying event from being rewarded twice.",
                        max_length=190,
                        null=True,
                        unique=True,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "available_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date a pending reward becomes eligible for posting.",
                        null=True,
                    ),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("reversed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reversal_of",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversal_transaction",
                        to="majestian_economy.cointransaction",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="majestian_economy.majestianwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coin transaction",
                "verbose_name_plural": "Coin transactions",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="MajestianRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("citizen", "Citizen"),
                            ("merchant", "Merchant"),
                            ("creator", "Creator"),
                            ("nonprofit", "Nonprofit"),
                            ("organization", "Organization"),
                            ("city", "City"),
                            ("festival", "Festival"),
                            ("kingdom", "Kingdom"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="citizen",
                        max_length=20,
                    ),
                ),
                ("membership_name", models.CharField(blank=True, max_length=120)),
                (
                    "membership_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reward_percentage_snapshot",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0.000"), max_digits=6
                    ),
                ),
                (
                    "reward_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "coins_awarded",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tracked", "Tracked"),
                            ("pending_payment", "Pending payment"),
                            ("payment_confirmed", "Payment confirmed"),
                            ("reward_pending", "Reward pending"),
                            ("rewarded", "Rewarded"),
                            ("rejected", "Rejected"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="tracked",
                        max_length=25,
                    ),
                ),
                (
                    "referral_code",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, db_index=True, max_length=190),
                ),
                ("payment_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("fraud_review_required", models.BooleanField(default=False)),
                ("fraud_review_notes", models.TextField(blank=True)),
                ("administrator_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "citizen_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="majestian_economy.citizenlevelreward",
                    ),
                ),
                (
                    "referred_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="majestian_recommendation_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="majestian_recommendations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendation",
                        to="majestian_economy.cointransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Majestian recommendation",
                "verbose_name_plural": "Majestian recommendations",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("membership_amount__gte", 0)),
                        name="recommendation_membership_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reward_percentage_snapshot__gte", 0)),
                        name="recommendation_percentage_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reward_value__gte", 0)),
                        name="recommendation_reward_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coins_awarded__gte", 0)),
                        name="recommendation_coins_nonnegative",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="majestianwallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("available_coins__gte", 0)),
                name="majestian_wallet_available_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="majestianwallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("pending_coins__gte", 0)),
                name="majestian_wallet_pending_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="majestianwallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("lifetime_earned_coins__gte", 0)),
                name="majestian_wallet_earned_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(
                fields=["wallet", "status", "created_at"],
                name="mc_wallet_status_created",
            ),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(
                fields=["transaction_type", "status"], name="mc_type_status"
            ),
        ),
        migrations.AddIndex(
            model_name="cointransaction",
            index=models.Index(
                fields=["reference_type", "reference_id"], name="mc_reference"
            ),
        ),
        migrations.AddConstraint(
            model_name="cointransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("coin_amount__gt", 0)),
                name="coin_transaction_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cointransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("coin_value_snapshot__gt", 0)),
                name="coin_transaction_value_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cointransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform_value__gte", 0)),
                name="coin_transaction_platform_nonnegative",
            ),
        ),
    ]
