# Generated by Django 5.2.3 on 2026-09-10 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MegaverseAuthorizationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("destination", models.CharField(db_index=True, max_length=100)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorization_codes",
                        to="integrations.megaverseidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "MajicMall Megaverse Authorization Code",
                "verbose_name_plural": "MajicMall Megaverse Authorization Codes",
                "indexes": [
                    models.Index(
                        fields=["destination", "expires_at"],
                        name="meg_auth_dest_exp_idx",
                    )
                ],
            },
        ),
    ]
